slam_toolbox:
  ros__parameters:

    # --- Plugin params ---
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # --- Core ROS Parameters ---
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping  # can change to 'localization' later if needed
    use_sim_time: true  # ✅ important when using Gazebo time

    debug_logging: false

    # --- Timing and Buffer Tweaks ---
    throttle_scans: 1                     # process every scan
    transform_publish_period: 0.05        # publish TF at 20 Hz
    map_update_interval: 0.5
    resolution: 0.05
    transform_timeout: 1.0                # ✅ increase TF wait time (fixes drop)
    tf_buffer_duration: 60.0              # ✅ keep TF history longer
    minimum_time_interval: 0.01            # ✅ accept faster scans
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # --- Range settings ---
    min_laser_range: 0.01
    max_laser_range: 4.0                  # ✅ extended for typical small maps

    # --- General Mapping Parameters ---
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.3          # ✅ respond faster to movement
    minimum_travel_heading: 0.3           # ✅ smaller rotation threshold
    scan_buffer_size: 50                  # ✅ larger buffer to prevent drops
    scan_buffer_maximum_scan_distance: 4.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # --- Correlation Parameters (matching performance) ---
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # --- Loop Closure Parameters ---
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # --- Scan Matcher Parameters ---
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    
    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1
